-- Definition: Percentage of revenue generated by top 20% of products.

-- Why: Validates whether 80/20 holds; helps focus on top SKUs.

-- Task: Compute revenue per product, rank by revenue; compute sum of revenue contributed by top 20% of products and show percent of total revenue.

-- How to approach 
-- First we need to compute revenue per product with orderdetails and products tables
-- Then we'll rank the products along with the total products
-- On the ranked dataset, we'll calculate the total and percentages

WITH product_revenue as (
SELECT 
	p.productcode,
  	p.productname,
    ROUND(SUM(od.priceeach * od.quantityordered), 2) AS revenue
FROM
	orderdetails od
JOIN
    products p USING(productcode)
GROUP BY
	1
),

ranked_revenue AS (
select 
	*,
  	RANK() OVER(ORDER BY revenue DESC) AS _rank,
    COUNT() OVER() AS total_products
FROM product_revenue
)

SELECT 
	(SELECT COUNT(*) FROM ranked_revenue WHERE _rank <= total_products*0.2) AS top_products,
    (SELECT SUM(revenue) FROM ranked_revenue WHERE _rank <= total_products*0.2) AS top_revenue,
    (SELECT SUM(revenue) FROM ranked_revenue) as total_revenue,
    ROUND((SELECT SUM(revenue) from ranked_revenue WHERE _rank <= total_products*0.2) * 100 / (SELECT SUM(revenue) FROM ranked_revenue), 2) AS pct_of_total
FROM ranked_revenue
LIMIT 1

-- There we had to think a little bit. See you in the next KPI